name: 'Playwright tests'

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run playwright tests'
        run: |
          docker-compose up -exit-code-from tests
      - name: 'Upload test results'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
