name: 'Playwright tests on push'

on:
  push:
    branches:
      - lec29-docker

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Playwright tests
        run: |
          docker-compose up --exit-code-from tests
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: playwright-report/
